"""Phase 3 — Tool-Calling SFT.

Trains LoRA adapters (projection frozen from Phase 2) on function-calling data
so the model learns to emit structured ``<tool_call>`` blocks for DocWain's
9 core document intelligence tools.

Data sources include synthetic tool-call traces generated by the V2 pipeline,
plus external benchmarks (ToolBench, Gorilla, NexusRaven) adapted to DocWain's
schema.

Typical wall-time: ~4-6 hours on a single A100-80 GB.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from .tool_data_generator import build_tool_calling_dataset

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass
class Phase3Config:
    """Hyperparameters for Phase 3 tool-calling SFT."""

    # LoRA
    lora_r: int = 64
    lora_alpha: int = 128
    lora_dropout: float = 0.0
    lora_target_modules: List[str] = field(default_factory=lambda: [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ])

    # Training
    learning_rate: float = 1e-5
    epochs: int = 5
    per_device_batch_size: int = 4
    max_seq_length: int = 4096
    warmup_ratio: float = 0.10
    weight_decay: float = 0.01
    gradient_accumulation_steps: int = 8
    max_grad_norm: float = 1.0
    bf16: bool = True
    lr_scheduler_type: str = "cosine"
    checkpoint_steps: int = 200

    # Projection freeze flag
    freeze_projection: bool = True

    # Data sources
    data_sources: List[str] = field(default_factory=lambda: [
        "synthetic",
        "toolbench",
        "gorilla",
        "nexusraven",
    ])
    data_dir: Path = Path("finetune_data/v2/tool_calling")
    phase2_dir: Path = Path("finetune_artifacts/v2/phase2.5")

    # Output
    output_dir: Path = Path("finetune_artifacts/v2/phase3")
    save_steps: int = 200
    logging_steps: int = 25
    eval_steps: int = 200

    # Quality gates — minimum metrics to proceed to Phase 4 (merge)
    gate_tool_accuracy: float = 0.85
    gate_arg_correctness: float = 0.90
    gate_false_positive_rate: float = 0.10

    # Source weights for mixing — must sum to 1.0
    source_weights: Dict[str, float] = field(default_factory=lambda: {
        "synthetic": 0.40,
        "toolbench": 0.25,
        "gorilla": 0.20,
        "nexusraven": 0.15,
    })


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _build_training_args(config: Phase3Config, output_dir: Path) -> Dict:
    """Build a SFTTrainer-compatible training arguments dictionary.

    Parameters
    ----------
    config:
        Phase 3 training configuration.
    output_dir:
        Directory where checkpoints and final model are written.

    Returns
    -------
    dict suitable for unpacking into ``trl.SFTConfig`` or
    ``transformers.TrainingArguments``.
    """
    return {
        "output_dir": str(output_dir),
        "num_train_epochs": config.epochs,
        "per_device_train_batch_size": config.per_device_batch_size,
        "gradient_accumulation_steps": config.gradient_accumulation_steps,
        "learning_rate": config.learning_rate,
        "lr_scheduler_type": config.lr_scheduler_type,
        "warmup_ratio": config.warmup_ratio,
        "weight_decay": config.weight_decay,
        "max_grad_norm": config.max_grad_norm,
        "bf16": config.bf16,
        "fp16": False,
        "logging_steps": config.logging_steps,
        "save_steps": config.checkpoint_steps,
        "eval_steps": config.eval_steps,
        "max_seq_length": config.max_seq_length,
        "dataset_text_field": "text",
        "report_to": "none",
        "seed": 42,
    }


# ---------------------------------------------------------------------------
# Training entrypoint
# ---------------------------------------------------------------------------


def run_phase3(
    config: Optional[Phase3Config] = None,
    *,
    phase2_dir: Optional[Path] = None,
) -> Path:
    """Execute Phase 3 tool-calling SFT.

    1. Loads the vision encoder + projection + LoRA from Phase 2.5 checkpoint.
    2. Freezes the projection (keep doc-intel alignment).
    3. Continues LoRA training on tool-calling data.
    4. Evaluates tool accuracy, argument correctness, and false-positive rate.
    5. Saves final adapters to ``config.output_dir``.

    Parameters
    ----------
    config:
        Training configuration. Uses defaults if ``None``.
    phase2_dir:
        Override path to the Phase 2.5 output directory.

    Returns
    -------
    Path to the output directory containing the final adapters.
    """
    if config is None:
        config = Phase3Config()

    p2_dir = phase2_dir or config.phase2_dir
    config.output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("=== Phase 3: Tool-Calling SFT ===")
    logger.info(
        "LoRA r=%d  alpha=%d  LR=%s  epochs=%d  batch=%d",
        config.lora_r,
        config.lora_alpha,
        config.learning_rate,
        config.epochs,
        config.per_device_batch_size,
    )
    logger.info("Data sources: %s  weights: %s", config.data_sources, config.source_weights)

    # --- Load model from Phase 2.5 checkpoint --------------------------------
    from .vision_graft import GraftConfig, VisionGraftedModel

    graft_cfg = GraftConfig(freeze_vision=True, freeze_text=False)
    model = VisionGraftedModel(graft_cfg)
    model.load_vision_encoder()

    proj_ckpt = p2_dir / "projection.pt"
    model.load_projection(checkpoint=proj_ckpt)

    # Freeze projection — only LoRA should learn tool-calling patterns
    if config.freeze_projection and model._projection is not None:
        for p in model._projection.parameters():
            p.requires_grad = False
        logger.info("Projection MLP frozen for Phase 3 training.")

    model.load_text_model()
    model.add_lora(r=config.lora_r, lora_alpha=config.lora_alpha)

    # --- Load tool-calling dataset -------------------------------------------
    logger.info("Building tool-calling dataset from sources: %s", config.data_sources)

    dataset_path = config.data_dir / "tool_calling_sft.jsonl"
    build_tool_calling_dataset(dataset_path)
    logger.info("Tool-calling dataset written to %s", dataset_path)

    from .tool_schemas import format_tools_for_prompt
    tools_json = format_tools_for_prompt()
    logger.info(
        "Embedding %d tool schemas in training prompts",
        len(tools_json.split('"name"')) - 1,
    )

    try:
        from datasets import load_dataset  # type: ignore
        dataset = load_dataset("json", data_files=str(dataset_path), split="train")
        logger.info("Loaded %d tool-calling training examples.", len(dataset))
    except Exception as exc:  # noqa: BLE001
        logger.warning("Failed to load tool-calling dataset (%s) — skipping training.", exc)
        dataset = None

    # --- Training loop (SFTTrainer) -------------------------------------------
    logger.info("Starting tool-calling SFT training...")

    try:
        from trl import SFTConfig, SFTTrainer  # type: ignore
    except ImportError:
        logger.error("trl is not installed. Install with: pip install trl>=0.8")
        raise

    if dataset is not None:
        training_args_dict = _build_training_args(config, config.output_dir)
        sft_cfg = SFTConfig(**training_args_dict)

        trainer = SFTTrainer(
            model=model._text_model,
            tokenizer=model._tokenizer,
            train_dataset=dataset,
            args=sft_cfg,
        )

        logger.info("Training Phase 3 for %d epochs...", config.epochs)
        trainer.train()

        final_ckpt = config.output_dir / "checkpoint_final"
        model._text_model.save_pretrained(str(final_ckpt))
        if model._tokenizer is not None:
            model._tokenizer.save_pretrained(str(final_ckpt))
        logger.info("Final checkpoint saved to %s", final_ckpt)
    else:
        logger.warning("No dataset available — skipping SFTTrainer run.")

    # --- Save outputs ---------------------------------------------------------
    model.save_all(config.output_dir)

    marker = config.output_dir / ".phase3_complete"
    marker.touch()
    logger.info("Phase 3 complete — artifacts saved to %s", config.output_dir)

    return config.output_dir
