"""Quantize DocWain-14B-v2 to W4A16 (AWQ-style 4-bit weights) using llm-compressor.

Run mode: CPU-offload — keeps vLLM-fast running on the A100 throughout.

Output: models/DocWain-14B-v2-AWQ/ (~7-8 GB safetensors in
`compressed-tensors` format, loaded by vLLM with `--quantization compressed-tensors`).

Per `feedback_no_customer_data_training.md`: synthetic calibration only.
The corpus (`data/awq_calibration/calibration_v1.jsonl`) is generated by
scripts/awq_calibration_corpus.py — 256 samples across 6 domains.

Usage:
  python scripts/quantize_v2_awq.py [--max-samples 256] [--no-gpu]

Logs: stdout + finetune_artifacts/awq_quant_v2/quant.log.
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(levelname)s %(name)s - %(message)s",
)
logger = logging.getLogger("awq-quant")


def load_calibration(path: Path, max_samples: int) -> list[dict]:
    samples: list[dict] = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            try:
                obj = json.loads(line)
                if "text" in obj:
                    samples.append(obj)
            except Exception:
                continue
            if len(samples) >= max_samples:
                break
    return samples


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default="models/DocWain-14B-v2")
    parser.add_argument("--output", default="models/DocWain-14B-v2-AWQ")
    parser.add_argument("--calibration",
                        default="data/awq_calibration/calibration_v1.jsonl")
    parser.add_argument("--max-samples", type=int, default=256)
    parser.add_argument("--max-seq-len", type=int, default=512)
    parser.add_argument("--no-gpu", action="store_true",
                        help="Force CPU-only (slower but no GPU contention)")
    args = parser.parse_args()

    src = Path(args.source).resolve()
    out = Path(args.output).resolve()
    cal = Path(args.calibration).resolve()
    log_dir = Path("finetune_artifacts/awq_quant_v2")
    log_dir.mkdir(parents=True, exist_ok=True)

    if not src.exists():
        logger.error("Source model not found: %s", src)
        return 2
    if not cal.exists():
        logger.error("Calibration not found: %s", cal)
        return 2

    logger.info("Source:      %s", src)
    logger.info("Output:      %s", out)
    logger.info("Calibration: %s", cal)
    logger.info("Mode:        %s", "CPU-only" if args.no_gpu else "auto (CPU offload)")

    if args.no_gpu:
        os.environ["CUDA_VISIBLE_DEVICES"] = ""

    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM
    from llmcompressor import oneshot
    from llmcompressor.modifiers.quantization import GPTQModifier
    from llmcompressor.modifiers.transform.smoothquant import SmoothQuantModifier

    calibration = load_calibration(cal, args.max_samples)
    logger.info("Loaded %d calibration samples", len(calibration))

    logger.info("Loading tokenizer")
    tok = AutoTokenizer.from_pretrained(str(src), trust_remote_code=True)

    logger.info("Loading model in fp16 (low_cpu_mem_usage, cpu device map)")
    t0 = time.time()
    model = AutoModelForCausalLM.from_pretrained(
        str(src),
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        device_map="cpu" if args.no_gpu else "auto",
        trust_remote_code=True,
    )
    logger.info("Model loaded in %.1fs", time.time() - t0)

    # Tokenize calibration samples for the dataset format llm-compressor expects
    logger.info("Tokenizing calibration corpus")
    def _to_input(sample: dict) -> dict:
        return tok(
            sample["text"],
            truncation=True,
            max_length=args.max_seq_len,
            padding=False,
            return_tensors="pt",
        )
    from datasets import Dataset
    raw = [_to_input(s) for s in calibration]
    ds = Dataset.from_list([
        {"input_ids": r["input_ids"][0].tolist(),
         "attention_mask": r["attention_mask"][0].tolist()}
        for r in raw
    ])

    # Recipe: SmoothQuant + GPTQ W4A16 (AWQ-equivalent quality, modern path)
    recipe = [
        SmoothQuantModifier(smoothing_strength=0.8),
        GPTQModifier(
            scheme="W4A16",
            targets="Linear",
            ignore=["lm_head"],
        ),
    ]

    logger.info("Starting one-shot quantization (W4A16) — long step, expect 1-3h GPU / 6-12h CPU")
    t0 = time.time()
    try:
        oneshot(
            model=model,
            tokenizer=tok,
            dataset=ds,
            recipe=recipe,
            max_seq_length=args.max_seq_len,
            num_calibration_samples=len(calibration),
            output_dir=str(out),
        )
    except Exception as exc:
        logger.exception("Quantization failed: %s", exc)
        return 3

    elapsed = time.time() - t0
    logger.info("Quantization complete in %.1fs (%.1f min)", elapsed, elapsed / 60)

    # Drop a marker for the deploy step
    marker = out / "AWQ_QUANT_INFO.json"
    with open(marker, "w") as fh:
        json.dump({
            "source": str(src),
            "calibration": str(cal),
            "calibration_samples": len(calibration),
            "scheme": "W4A16 (compressed-tensors via llm-compressor)",
            "recipe": "SmoothQuant(0.8) + GPTQ(W4A16, ignore=lm_head)",
            "completed_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "mode": "cpu" if args.no_gpu else "auto",
            "elapsed_seconds": int(elapsed),
        }, fh, indent=2)

    logger.info("Done. Quantized artifact at %s", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
